name: flutter_icomoon_icons
description: 490 Free IcoMoon Icons for Flutter for directly using in both Android/iOS
version: 1.0.0
author: Rishi Banerjee <rishieric91@gmail.com>
homepage: https://github.com/rshrc/flutter_icomoon_icons

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  recase: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: IcoMoon
      fonts:
        - asset: fonts/icomoonfree.ttf
